### ISSUE TITLE
Explain CLI commands in the documentation

### ISSUE THREAD

**Issue by Samuelopez-ansys** [ansys/aedt-testing#127]
I think CLI commands should be documented in the "Usage" section like the Configuration File section. I could do it if you agree  @beliaev-maksim , @boyang2022

**Comment by beliaev-maksim** [comment]
@Samuelopez-ansys 
sure, we can do it as well

also do not hesitate to change built-in help for CLI. 
eg when you call `aedt_test_runner -h`
