### ISSUE TITLE
reference profiles are not copied

### ISSUE THREAD

**Issue by beliaev-maksim** [ansys/aedt-testing#187]
I think it is better to copy all reference profiles, since otherwise user cannot copy and share results folder

also,
currently link does not work, only if you open in new browser tab.  I assume it is due to a small `c:\\` as a drive letter

**Comment by Samuelopez-ansys** [comment]
Hi @beliaev-maksim ,

What do you mean?

Now, all reference profiles are copied to the new reference folder, the saved path in the JSON file is relative so it does not contain the c:\\. Please could you describe how to reproduce the issue?

**Comment by beliaev-maksim** [comment]
@Samuelopez-ansys 
I see the code, but when I run e2e tests I do not see that profiles were copied and also hyperlinks point outside of results folder
