### ISSUE TITLE
PyAEDT errors are not showed in HTML

### ISSUE THREAD

**Issue by Samuelopez-ansys** [ansys/aedt-testing#210]

**Comment by beliaev-maksim** [comment]
Here is the question what are the errors you would like to see. We explicitly disabled logs from pyaedt and see it only with `--debug` flag

**Comment by Samuelopez-ansys** [comment]
@beliaev-maksim PyAEDT logger changed and in simulation_data.py we were saving the error_messages from:

app.logger.get_messages

Which it is returning an object. We modified it to return the error messages returned in AEDT. Then the HTML returned this error message:
![image](https://user-images.githubusercontent.com/85613111/185144654-1accae7d-dad3-4a05-bd03-c9120ecdc56b.png)


So with the fix, if a project fails, the HTML will contain this info (working as expected):
![image](https://user-images.githubusercontent.com/85613111/185144497-f927c769-8c47-4404-b998-1fb0ca865e9f.png)

**Comment by beliaev-maksim** [comment]
Makes sense!
