### ISSUE TITLE
module 'clr_loader' has no attribute 'wrappers'

### ISSUE THREAD

**Issue by boyang2022** [ansys/aedt-testing#218]
@Samuelopez-ansys @beliaev-maksim 
Any idea about this module clr_loader? Failed at unit test. 

I also encounter this.

**Comment by beliaev-maksim** [comment]
What is the context?

Smth from pyaedt?

**Comment by boyang2022** [comment]
seems the issue with pythonnet.

![image](https://user-images.githubusercontent.com/93125854/201044687-40cdabaa-73e3-4efd-bd72-0625359b8b90.png)

shall we add pythonnet==3.0.1 in dependency?

**Comment by beliaev-maksim** [comment]
looks like it is coming from pyaedt


try bumping pyaedt version to see if that fixes
if not, then a bug in pyaedt to be addressed
