### ISSUE TITLE
HFSS 3D Layout is not supported

### ISSUE THREAD

**Issue by hui-zhou-a** [ansys/aedt-testing#222]
aedb is not copied into test folder. It leads to error

**Comment by beliaev-maksim** [comment]
do you use metadata in config file to attach supportive files ?

**Comment by ring630** [comment]
@beliaev-maksim you are correct. When aedb is added in dependencies list, the problem is solved. However, .aedb folder is always part of 3dlayout desgin. It is wired to ask the user to add it manually. I made a modification to include aedb by default. I will push it soon.

**Comment by ring630** [comment]
@beliaev-maksim OK. I am not part of the project...

**Comment by beliaev-maksim** [comment]
do a forr and push it ;)
